### ISSUE TITLE
Deprication of in-toto-golang - Tracker

### ISSUE THREAD

**Issue by 06kellyjac** [in-toto/in-toto-golang#369]
The plan for a while now has been to deprecate https://github.com/in-toto/in-toto-golang in favor of the https://github.com/in-toto/go-witness library.

Actions required for deprecation and eventual archiving of the repo:

* [X] Create a tracker issue for recording progress/status
* [ ] Pin the tracker issue
* [ ] Add identifiers to the code to be found by code quality scanners
* [ ] Add a notice on the README
* [ ] Add simple examples to facilitate migrations
* [ ] Discuss cutting a v1 of in-toto/go-witness
* [ ] Decide a date to stop updating dependencies
* [ ] Decide a date to archive the repo (locks issues etc)
* [ ] Archive

Light discussion is welcome in the issue. If conversations are very active we will look to break out into separate descriptions

**Comment by shibumi** [comment]
I pinned the tracker issue.
